name: Proof HTML, Lint JS & CSS

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write # Needed to commit back changes

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Remove or comment this out completely — no static HTML to validate
      # - name: Validate HTML and CSS
      #   uses: anishathalye/proof-html@v2
      #   with:
      #     directory: ./site

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install eslint stylelint stylelint-config-standard --save-dev

      - name: Fix JavaScript issues
        run: |
          npx eslint assets/js/**/*.js --fix

      - name: Fix CSS issues
        run: |
          npx stylelint assets/css/**/*.css --fix

      - name: Commit fixes (if any)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/js assets/css || true
          git diff --cached --quiet || git commit -m "chore: auto-fix JS/CSS lint issues"
          git push
